### PR TITLE
No type script version

### LINKED ISSUE #1: Updated demo to use MSAL 3.1.0
currently the demo is using version 2.30.0. there have been some major changes to the MSAL-browser library in version 3.1.0

### PR DESCRIPTION
**Pull request by iamexe**
Adds a ".No TypeScript Version" folder to the main msal-vue-demo repo.
The contents of which are a working implementation of msal-vue-demo without using TypeScript.

This pull request contains the fix #1 for 3.1 support.

This version of the app replaces the api service and user view with a dashboard view that uses a stacked Vue Chart JS Bar component with tooltip filter and functions together with some sample data that replace what would otherwise come from an Express.js backend.

### CODE REVIEW

**Comment by davestewart** [comment]
Hey there,

Thanks for the PR but won't merge this; TS is a prerequisite on almost any non-trivial project these days 😊

I am though, happy to link to your GH fork from the main blog article, if perhaps you want to clean it up (I guess, replace those files in the root?).

LMK!

PS Y U not know TS in 2023?
PPS It's actually pretty easy to learn!

**Comment by iamexe** [comment]
Hey,

thanks for the feedback! I cleaned up the fork so please link it if you want.

I tried using TS but then ran into very frustrating issues with the Vue ChartJS Chart Options and it was frustrating to me because I felt like I'm spending hours to research cryptic TS error messages of code that would work just fine for it's intended purposes.

"Easy things become difficult and difficult things become any" ;-) 

TS really took out some of the joy for me. 
Even if I had everything in TS - what do I gain? 
I don't care about type safety or autocomplete.

I'm willing to give it a try in the future however. 
Idially I want to get to the point where I like TS (now I hate it).

How would the following code look in TS? I would have to rewrite the helper functions in TS. 
I tried but got stuck because I didn't know if I really had to describe fully the structure (type) of the options object.
I tried to import the type from the Chart JS or Vue Chart JS library but that didn't work either for some reason.
Then I learned instead of rewritting the md5 function into TS I could exclude it from TypeScript... but at that point, what's the point?

```js
      options: {
        interaction: {
          intersect: false,
          mode: 'x',
        },
        plugins: {
          tooltip: {
            filter: function (tooltipItem) { 
              return tooltipItem.dataset.data[tooltipItem.dataIndex] > 0; 
            },
            callbacks: {
              footer: helpers.tooltipFooter, 
            },
          }
        },
        responsive: true,
        scales: {
          x: {
            stacked: true,
          },
          y: {
            stacked: true,
            beginAtZero: true,
            title: {
              display: true,
              text: 'CHF', 
            },
          }
        }
      },
```

helpers.tooltipFooter function:

```js
const tooltipFooter = (tooltipItems) => {
  let sum = 0;
  tooltipItems.forEach(function(tooltipItem) {
    sum += tooltipItem.parsed.y;
  });
  return 'CHF ' + sum;
};
```

Then this:

```js
    const datasets = Object.keys(pricesByService).map((service) => ({
      label: service,
      backgroundColor: helpers.stringToColor(service),
      data: customerNames.map((customerName) =>
        pricesByService[service][customerName] || 0
      ),
    }));
```

helpers.stringToColor function:

```js
const stringToColor = (str) => {
  let md5string = md5(str);
  let color =  `#${md5string.slice(0, 6)}`;
  return color;
}
```

```js
// md5 function by [dkellner](https://stackoverflow.com/users/1892607/dkellner) 
const md5 = (inputString) => {
  var hc="0123456789abcdef";
  function rh(n) {var j,s="";for(j=0;j<=3;j++) s+=hc.charAt((n>>(j*8+4))&0x0F)+hc.charAt((n>>(j*8))&0x0F);return s;}
  function ad(x,y) {var l=(x&0xFFFF)+(y&0xFFFF);var m=(x>>16)+(y>>16)+(l>>16);return (m<<16)|(l&0xFFFF);}
  function rl(n,c)            {return (n<<c)|(n>>>(32-c));}
  function cm(q,a,b,x,s,t)    {return ad(rl(ad(ad(a,q),ad(x,t)),s),b);}
  function ff(a,b,c,d,x,s,t)  {return cm((b&c)|((~b)&d),a,b,x,s,t);}
  function gg(a,b,c,d,x,s,t)  {return cm((b&d)|(c&(~d)),a,b,x,s,t);}
  function hh(a,b,c,d,x,s,t)  {return cm(b^c^d,a,b,x,s,t);}
  function ii(a,b,c,d,x,s,t)  {return cm(c^(b|(~d)),a,b,x,s,t);}
  function sb(x) {
      var i;var nblk=((x.length+8)>>6)+1;var blks=new Array(nblk*16);for(i=0;i<nblk*16;i++) blks[i]=0;
      for(i=0;i<x.length;i++) blks[i>>2]|=x.charCodeAt(i)<<((i%4)*8);
      blks[i>>2]|=0x80<<((i%4)*8);blks[nblk*16-2]=x.length*8;return blks;
  }
  var i,x=sb(""+inputString),a=1732584193,b=-271733879,c=-1732584194,d=271733878,olda,oldb,oldc,oldd;
  for(i=0;i<x.length;i+=16) {olda=a;oldb=b;oldc=c;oldd=d;
      a=ff(a,b,c,d,x[i+ 0], 7, -680876936);d=ff(d,a,b,c,x[i+ 1],12, -389564586);c=ff(c,d,a,b,x[i+ 2],17,  606105819);
      b=ff(b,c,d,a,x[i+ 3],22,-1044525330);a=ff(a,b,c,d,x[i+ 4], 7, -176418897);d=ff(d,a,b,c,x[i+ 5],12, 1200080426);
      c=ff(c,d,a,b,x[i+ 6],17,-1473231341);b=ff(b,c,d,a,x[i+ 7],22,  -45705983);a=ff(a,b,c,d,x[i+ 8], 7, 1770035416);
      d=ff(d,a,b,c,x[i+ 9],12,-1958414417);c=ff(c,d,a,b,x[i+10],17,     -42063);b=ff(b,c,d,a,x[i+11],22,-1990404162);
      a=ff(a,b,c,d,x[i+12], 7, 1804603682);d=ff(d,a,b,c,x[i+13],12,  -40341101);c=ff(c,d,a,b,x[i+14],17,-1502002290);
      b=ff(b,c,d,a,x[i+15],22, 1236535329);a=gg(a,b,c,d,x[i+ 1], 5, -165796510);d=gg(d,a,b,c,x[i+ 6], 9,-1069501632);
      c=gg(c,d,a,b,x[i+11],14,  643717713);b=gg(b,c,d,a,x[i+ 0],20, -373897302);a=gg(a,b,c,d,x[i+ 5], 5, -701558691);
      d=gg(d,a,b,c,x[i+10], 9,   38016083);c=gg(c,d,a,b,x[i+15],14, -660478335);b=gg(b,c,d,a,x[i+ 4],20, -405537848);
      a=gg(a,b,c,d,x[i+ 9], 5,  568446438);d=gg(d,a,b,c,x[i+14], 9,-1019803690);c=gg(c,d,a,b,x[i+ 3],14, -187363961);
      b=gg(b,c,d,a,x[i+ 8],20, 1163531501);a=gg(a,b,c,d,x[i+13], 5,-1444681467);d=gg(d,a,b,c,x[i+ 2], 9,  -51403784);
      c=gg(c,d,a,b,x[i+ 7],14, 1735328473);b=gg(b,c,d,a,x[i+12],20,-1926607734);a=hh(a,b,c,d,x[i+ 5], 4,    -378558);
      d=hh(d,a,b,c,x[i+ 8],11,-2022574463);c=hh(c,d,a,b,x[i+11],16, 1839030562);b=hh(b,c,d,a,x[i+14],23,  -35309556);
      a=hh(a,b,c,d,x[i+ 1], 4,-1530992060);d=hh(d,a,b,c,x[i+ 4],11, 1272893353);c=hh(c,d,a,b,x[i+ 7],16, -155497632);
      b=hh(b,c,d,a,x[i+10],23,-1094730640);a=hh(a,b,c,d,x[i+13], 4,  681279174);d=hh(d,a,b,c,x[i+ 0],11, -358537222);
      c=hh(c,d,a,b,x[i+ 3],16, -722521979);b=hh(b,c,d,a,x[i+ 6],23,   76029189);a=hh(a,b,c,d,x[i+ 9], 4, -640364487);
      d=hh(d,a,b,c,x[i+12],11, -421815835);c=hh(c,d,a,b,x[i+15],16,  530742520);b=hh(b,c,d,a,x[i+ 2],23, -995338651);
      a=ii(a,b,c,d,x[i+ 0], 6, -198630844);d=ii(d,a,b,c,x[i+ 7],10, 1126891415);c=ii(c,d,a,b,x[i+14],15,-1416354905);
      b=ii(b,c,d,a,x[i+ 5],21,  -57434055);a=ii(a,b,c,d,x[i+12], 6, 1700485571);d=ii(d,a,b,c,x[i+ 3],10,-1894986606);
      c=ii(c,d,a,b,x[i+10],15,   -1051523);b=ii(b,c,d,a,x[i+ 1],21,-2054922799);a=ii(a,b,c,d,x[i+ 8], 6, 1873313359);
      d=ii(d,a,b,c,x[i+15],10,  -30611744);c=ii(c,d,a,b,x[i+ 6],15,-1560198380);b=ii(b,c,d,a,x[i+13],21, 1309151649);
      a=ii(a,b,c,d,x[i+ 4], 6, -145523070);d=ii(d,a,b,c,x[i+11],10,-1120210379);c=ii(c,d,a,b,x[i+ 2],15,  718787259);
      b=ii(b,c,d,a,x[i+ 9],21, -343485551);a=ad(a,olda);b=ad(b,oldb);c=ad(c,oldc);d=ad(d,oldd);
  }
  return rh(a)+rh(b)+rh(c)+rh(d);
}
```

EDIT: I want to emphasize that I would really like to learn TS and start to like it but it was frustrating not being able to describe that options object and knowing that if it weren't for the TS complains it would work.

**Comment by davestewart** [comment]
Hey hey,

Well, well done for giving it a go!

You are right that if you don't know "the thing" Typescript can be extremely frustrating.

I would say that you can learn 80% of "the things" in under an hour by simply going through the [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/intro.html) on the website. It is some of the best documentation out there, and by the time you're halfway through you will be so enthused the next page won't be able to come soon enough!

Once you get to things like utility classes, Records, generics, etc hopefully you'll be 🤯🤩🚀.

FWIW I cloned your code but of course it's all JS now, so there's no way to help with the issues you were having.

I suspect that if the chart props were typed correctly, you may have been passing in something you shouldn't.


- https://github.com/apertureless/vue-chartjs/blob/96680d66feb717428c4243549640c9a22c544bd8/src/props.ts#L12
- https://github.com/chartjs/Chart.js/blob/6516b0a150eebf3fb9eab596f89d63e27e1bc6d5/src/types/index.d.ts#L3789

The easiest way to check in these cases is to delete all the options back to an empty object then use `Ctrl+Space` or whatever you editor uses to show autocomplete and see what options are available to you.

Sometimes you need to type objects separately to see:

```ts
import { BarOptions } from 'chart-lib'

const options: BarOptions = {
  // can only enter properties of BarOptions here
}
```

You can then pass them in.

Vue and Nuxt also use "define" functions which are nice as you get the same thing from function parameters:

```ts
function defineThing(options: ThingOptions): Thing {
  // pass back a new Thing
}

const thing = defineThing({
  // can only enter properties of ThingOptions here
})
```

Not sure if that helps now, but at some point in your near future perhaps you'll go "Oh yeah, that's what Dave said!". 🤞

Final thing – adding charts and external libs (as you have found out) is exactly the thing I don't want for this repo! Adding authentication is enough of a f---ing drama without adding extra stuff for folks to trip over.

So, I guess I'll say, don't give up, keep chipping away and asking for help and you'll slowly slowly get there.

Final tip; consume everything [this guy puts out](https://www.youtube.com/@mattpocockuk/videos) (or do his [course](https://www.totaltypescript.com/)):

- https://www.youtube.com/watch?v=p6dO9u0M7MQ

He's a Wizard, Harry!

**Comment by iamexe** [comment]
Hey Dave

Thank you very much!

I may look into TypeScript on Thursday or Friday again. 
I needed a pause because I was really feeling the hate haha...

The sales text at totaltypescript is describing it flawlessly.

> "The feature’s working. The tests are passing.
> But your IDE is a sea of red lines. TypeScript’s not happy again.
> 
> You move on to the next error:
> 
> “What on earth is this?”
> 
> you think to yourself."

& 

> "The truth is that you never truly learned TypeScript, at least not in depth. That's the source of your pain." 

Yeah that's what I suspected intuitively. So I'll give [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/intro.html) a go and then check out the [YouTube video](https://www.youtube.com/watch?v=p6dO9u0M7MQ).

Oh and I subscribed to Harry's channel - so the algo will do it's duty in pushing TypeScript propaganda to me and hopefully in a month or two I will write TypeScript happily.

Offtopic: meanwhile some other beast was burning through my time the last two days. 
If you want more 'fun' look into getting CUDA on WSL2 with ollama running ...

**Pull request closed without merging**
